import localFont from "next/font/local";
import "./ui/globals.css";
// import Layout from "./dashboard/layout";

import styles from "../app/ui/dashboard/dashboard.module.css";
import { Sidebar } from "./ui/dashboard/sidebar/sidebar";
import { Navbar } from "./ui/dashboard/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={styles.container}>
          <div className={styles.menu}>
            <Sidebar />
          </div>
          <div className={styles.content}>
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
